### PR TITLE
group16_survival

### PR DESCRIPTION
**Pull request by CarsonSo**
update sample_project.rmd
Group 16: Haoxiong Su, Tianchun Huang
Content: Survival analysis in R

### CODE REVIEW

**Comment by ybliu9** [comment]
This pull request is trying to change the original sample_project.Rmd here.  You need to rename your file.

**Comment by tracy3057** [comment]
Please do not include the following part, I will help you delete it directly.

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Comment by tracy3057** [comment]
> This pull request is trying to change the original sample_project.Rmd here. You need to rename your file.

I have added this part in the chapter of 'Complete Analyses' for now, but I'm not sure whether it's suitable. Please help me check out. Thank you!

**Comment by jtr13** [comment]
Thank you for your contribution! 🎉

**Pull request merged**
