### PR TITLE
add time series cheatsheet

### PR DESCRIPTION
**Pull request by gulingxuan98**

### CODE REVIEW

**Review by scaisijie — CHANGES_REQUESTED** [review]
Project name should be the same as the root directory name of the branch

**Comment by gulingxuan98** [comment]
Project renamed

**Comment by scaisijie** [comment]
Thanks for your contribution. Your work has been merged.

**Comment by jtr13** [comment]
Published chapter: https://jtr13.github.io/cc20/time-series-cheatsheet.html 🙌

**Pull request merged**
