### PR TITLE
Adding CC chapter describing a trivia night that I hosted

### PR DESCRIPTION
**Pull request by jingwendu**

### CODE REVIEW

**Review by andycho97 — CHANGES_REQUESTED** [review]
Please see the Rmd file formatting:

Project name should be the same as the root directory name of the branch, and should be words only and joined with underscores, no white space.

**Review by jingwendu — COMMENTED** [review]
Do I need to change my rmd file name or my branch name?  My rmd file name "american_history_trivia_night" does follow the format requested.  My branch name is "jingwen_du" because I thought it doesn't matter what the branch name is.

**Comment by andycho97** [comment]
Just the branch name - Project name (Rmd file) should be the same as the root directory name of the branch. So the branch name should be: american_history_trivia_night

**Comment by jingwendu** [comment]
I created a new pull request with a new branch name that matches my rmd file name.  All other materials remain the same. 
 Does this work?

https://github.com/jtr13/cc20/pull/109

**Pull request merged**
