### PR TITLE
 this is for Gaoyi Shi and Xiaonan Guo CC

### PR DESCRIPTION
**Pull request by xguo7013**

### CODE REVIEW

**Comment by cpaynerogers** [comment]
@ybliu9, I think this chapter is perfect for the updated "results reporting" (used to be R Shiny) chapter. I hadn't seen it, but this is what I had in mind for that section.

**Comment by ybliu9** [comment]
> @ybliu9, I think this chapter is perfect for the updated "results reporting" (used to be R Shiny) chapter. I hadn't seen it, but this is what I had in mind for that section.

Yes, agree. I am merging this contribution to the book.

**Comment by ybliu9** [comment]
Thanks a lot for your contribution!

**Comment by jtr13** [comment]
Published: https://jtr13.github.io/cc20/visualiztion-tools-in-real-work.html

**Pull request merged**
