### PR TITLE
benfords_law

### PR DESCRIPTION
**Pull request by mcryan6**
Benfords Law analysis of 2020 election. NYT national data. Michigan dept of elections precinct data.

### CODE REVIEW

**Comment by cpaynerogers** [comment]
This is currently tagged for the "complete analyses" chapter, but it looks like its narrowly focused on analysis and doesn't include any data processing or plotting code.

**Comment by mcryan6** [comment]
Can you not see the .html file? Should I paste the ipynb as well?[https://github.com/mcryan6/benfords_law_2020_election/blob/main/benfords_law_2020election.ipynb](url)

**Comment by cpaynerogers** [comment]
Hey Ryan, I can see the HTML, but when I visit the file in your GitHub it is "too big to display" and has to be shown [raw](https://raw.githubusercontent.com/mcryan6/benfords_law_2020_election/main/benfords_law_2020election.html). I'm not sure if or how it will be displayed once your chapter is merged into our book.

**Comment by jtr13** [comment]
It will just display as a link, which is what we want, however linking to the `.ipynb` is a better choice than the `.html` since it displays nicely on GitHub. (I'm assuming the content is the same.)

Also, you need to make this PR from a new branch not the master branch of your fork. Thanks!

**Comment by mcryan6** [comment]
Oops sorry I merged with master before pull request. 
But yes its the same content in html as ipynb. I'll close this pull request, make the change to point at the other link, then re-submit pull request from the branch.

**Pull request closed without merging**
