### PR TITLE
initial commit adding pdf

### PR DESCRIPTION
**Pull request by MirandaZhou98**

### CODE REVIEW

**Comment by cpaynerogers** [comment]
Marking this with "data visualization" chapter, but since its a PDF: should it be included in the section for "live tutorials" since it won't get accessed within the flow of reading a bookdown book?

**Comment by jtr13** [comment]
Live tutorials doesn't seem quite right but we could group the cheatsheets together depending on how many there are.

**Comment by cpaynerogers** [comment]
For now, I think Yibai and I will group cheat sheets and "live tutorials" together so we don't have *too* many sections. If we have a lot of submissions in each category we can split them. If we don't, they deserve a better name than "Live Tutorials."

**Review by andycho97 — CHANGES_REQUESTED** [review]
Please see below for the Rmd file formatting:

Project name should be the same as the root directory name of the branch, and should be words only and joined with underscores, no white space.

**Comment by andycho97** [comment]
@MirandaZhou98 let me know if you need clarification here

**Comment by andycho97** [comment]
(Update: It does not need to be the same as the branch name.) I will go ahead and process this

**Review by andycho97 — APPROVED** [review]
Please see below for the Rmd file formatting:

Project name should be the same as the root directory name of the branch, and should be words only and joined with underscores, no white space.

**Comment by MirandaZhou98** [comment]
Hello!! Sorry I'm having some trouble figuring out where to change... Is it ok now?

**Pull request merged**
