### PR TITLE
Mosaic plot cheatsheet initial commit.

### PR DESCRIPTION
**Pull request by Terrrry98**

### CODE REVIEW

**Comment by ybliu9** [comment]
I clicked on the link and saw two major files. 
Could you please 1) add a link to the cheatsheet pdf in your CC-group15.Rmd file, 2) change the format of your CC-group15.Rmd file and rename it to something like "mosaic_plot_cheatsheet.Rmd", and 3) commit the renamed file and make a pull request?
Then we will merge your contribution to the book :)

**Comment by ybliu9** [comment]
If you want you can close this PR and start over

**Comment by Terrrry98** [comment]
Hi Yibai,

Thank you for your email.

I saw last year some teams also did the cheatsheet things, like this one
https://jtr13.github.io/cc19/cheat-sheet-of-wordcloud2-package.html

What we did is basically the same which provides a link to the git repo
that contains the cheatsheet file in the pdf format and coding part.

This is because we use PowerPoint to make the cheatsheet and the coding
file(CC-group15.Rmd) is only used to generate figures. We supposed what
shows in the book is the description of what we did and a link to the repo.
Feel free to correct me if I'm wrong.

Best,
Liyuan Tang

**Comment by ybliu9** [comment]
Thanks for letting me know. That makes sense. If there isn't any other issue, the merger will help merge your work into the book.

**Comment by Terrrry98** [comment]
> Thanks for letting me know. That makes sense. If there isn't any other issue, the merger will help merge your work into the book.

Thank you for your help!

**Comment by ybliu9** [comment]
Thanks a lot for your contribution!

**Comment by jtr13** [comment]
Published: https://jtr13.github.io/cc20/mosaic-plot-cheatsheet.html

**Pull request merged**
